
    server {
    server_name late-planes-chew-daily.st.a.dcdg.xyz;

    location /threads {
        limit_req zone=thread_limit burst=1 nodelay;
        limit_req_status 429;

        proxy_pass http://localhost:5000;
    }

    location / {
        proxy_pass http://localhost:5000;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/late-planes-chew-daily.st.a.dcdg.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/late-planes-chew-daily.st.a.dcdg.xyz/privkey.pem;
}

server {
    listen 80;
    server_name late-planes-chew-daily.st.a.dcdg.xyz;

    return 301 https://$host$request_uri;
}
